Repository SWM14-Architect/moview-core-service, pull requests merged in 2023-11, with the labels that each got.

#143 !HOTFIX: 도커 컨테이너의 timezone 수정
  Dockerfile
Labels: hotfix

#144 Refactor/answer service and test
  moview/config/container/container_config.py
  moview/controller/answer_controller.py
  moview/environment/llm_factory.py
  moview/modules/light/light_question_giver.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/answer/__init__.py
  moview/service/answer/answer_service.py
  moview/service/answer/followup_question_determiner.py
  moview/service/answer/question_choosing_strategy.py
  moview/service/answer_service.py
  moview/service/interview_service.py
  moview/utils/mixin/__init__.py
  moview/utils/mixin/directory_mixin.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/light/test_light_question_giver.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/service/test_answer_service.py
  tests/service/test_light_mode_service.py
Labels: refactor, test, rename, remove

#148 Refactor: Initial Question Prompt
  README.md
  app.py
  moview/controller/health_controller.py
  moview/modules/input/initial_question_giver.py
  moview/service/answer/answer_service.py
  moview/service/input_data_service.py
  tests/modules/input/test_inital_question_giver.py
Labels: fix, doc s, refactor

#149 Release v3.3
  Dockerfile
  README.md
  app.py
  moview/config/container/container_config.py
  moview/controller/answer_controller.py
  moview/controller/health_controller.py
  moview/environment/llm_factory.py
  moview/modules/input/initial_question_giver.py
  moview/modules/light/light_question_giver.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/answer/__init__.py
  moview/service/answer/answer_service.py
  moview/service/answer/followup_question_determiner.py
  moview/service/answer/question_choosing_strategy.py
  moview/service/answer_service.py
  moview/service/input_data_service.py
  moview/service/interview_service.py
  moview/utils/mixin/__init__.py
  moview/utils/mixin/directory_mixin.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/light/test_light_question_giver.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/service/test_answer_service.py
  tests/service/test_light_mode_service.py
Labels: release

#150 Feat: 최종발표 시연용
  moview/service/answer/answer_service.py
  moview/service/input_data_service.py
Labels: feat

#151 Feat: 평가 양식 지정
  moview/controller/evaluation_controller.py
Labels: feat
