Repository SWM14-Architect/moview-core-service, pull requests merged in 2023-09, with the labels that each got.

#80 Refactor answer_2
  moview/domain/entity/interview_session_document.py
  moview/domain/entity/question_answer/__init__.py
  moview/domain/entity/question_answer/answer.py
  moview/domain/entity/question_answer/question.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  moview/modules/question_generator/answer_validator.py
  moview/modules/question_generator/followup_question_giver.py
  moview/repository/interview_repository.py
  moview/repository/question_answer/__init__.py
  moview/repository/question_answer/question_answer_repository.py
  moview/service/answer_service.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  tests/common_code_for_test.py
  tests/modules/question_generator/test_answer_category_classifier.py
  tests/modules/question_generator/test_answer_sub_category_classifier.py
  tests/modules/question_generator/test_answer_validator.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/repository/test_question_answer_repository.py
  tests/service/test_answer_service.py
Labels: fix, refactor, test

#81 Docs and remove unused
  README.md
  moview/__init__.py
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_feedback_controller.py
  moview/controller/interviewee_session_controller.py
  moview/controller/interviwee_input_controller.py
  moview/domain/entity/interviewee_data_main_document.py
  moview/domain/entity/interviewee_data_subdocument.py
  moview/repository/interviewee_data_repository.py
  moview/service/__init__.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_answer/interviewer_action_enum.py
  moview/service/interviewee_evaluation/__init__.py
  moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
  moview/service/interviewee_feedback/__init__.py
  moview/service/interviewee_feedback/interviewee_feedback_service.py
  moview/service/interviewee_input/__init__.py
  moview/service/interviewee_input/interviewee_input_service.py
  tests/config/__init__.py
  tests/config/handlers/__init__.py
  tests/config/handlers/test_mongo_handler.py
  tests/config/loggers/__init__.py
  tests/config/loggers/test_mongo_logger.py
  tests/repository/test_interviewee_data_repository.py
  tests/service/interviewee_answer/__init__.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_evaluation/__init__.py
  tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
  tests/service/interviewee_feedback/__init__.py
  tests/service/interviewee_feedback/test_interviewee_feedback_service.py
  tests/service/interviewee_input/__init__.py
  tests/service/interviewee_input/test_interviewee_input_service.py
Labels: doc s, remove

#82 Feat feedback
  moview/controller/dto/__init__.py
  moview/controller/dto/feedback_dto.py
  moview/repository/question_answer/question_answer_repository.py
  moview/service/answer_service.py
  moview/service/feedback_service.py
  tests/service/test_feedback_service.py
Labels: feat, test

#85 feat: dev 브랜치용 CI/CD 파이프라인 구성
  .github/workflows/dev_pr.yml
  .github/workflows/dev_push.yml
  .github/workflows/feat_push.yml
Labels: feat

#87 feat: dev 브랜치용 CI/CD 파이프라인 구성
  .github/workflows/dev_pr.yml
  .github/workflows/dev_push.yml
  .github/workflows/feat_push.yml
Labels: feat

#86 Remove answer modules
  README.md
  moview/config/container/container_config.py
  moview/controller/answer_controller.py
  moview/controller/dto/feedback_dto.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/domain/entity/question_answer/answer.py
  moview/environment/llm_factory.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  moview/modules/question_generator/answer_validator.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/answer_service.py
  moview/service/feedback_service.py
  moview/utils/prompt_parser.py
  requirements.txt
  tests/modules/async/__init__.py
  tests/modules/async/test_async_call.py
  tests/modules/question_generator/test_answer_category_classifier.py
  tests/modules/question_generator/test_answer_sub_category_classifier.py
  tests/modules/question_generator/test_answer_validator.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/repository/test_question_answer_repository.py
  tests/service/test_answer_service.py
  tests/service/test_feedback_service.py
  tests/utils/test_prompt_parser.py
Labels: fix, doc s, feat, test, remove

#88 feat: 초기데이터 관련 모듈 비동기 병렬처리 적용
  README.md
  moview/config/container/container_config.py
  moview/controller/answer_controller.py
  moview/controller/dto/feedback_dto.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/domain/entity/question_answer/answer.py
  moview/environment/llm_factory.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  moview/modules/question_generator/answer_validator.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/answer_service.py
  moview/service/feedback_service.py
  moview/service/input_data_service.py
  moview/utils/async_controller.py
  moview/utils/prompt_parser.py
  moview/utils/retry_decorator.py
  requirements.txt
  tests/modules/async/__init__.py
  tests/modules/async/test_async_call.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/input/test_input_analyzer.py
  tests/modules/question_generator/test_answer_category_classifier.py
  tests/modules/question_generator/test_answer_sub_category_classifier.py
  tests/modules/question_generator/test_answer_validator.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/repository/test_question_answer_repository.py
  tests/service/test_answer_service.py
  tests/service/test_feedback_service.py
  tests/service/test_input_service.py
  tests/utils/test_prompt_parser.py
Labels: doc s, refactor, feat

#92 feat: evaluation 기능 구현
  README.md
  moview/__init__.py
  moview/config/container/container_config.py
  moview/controller/evaluation_controller.py
  moview/domain/entity/question_answer/answer.py
  moview/environment/llm_factory.py
  moview/exception/__init__.py
  moview/exception/evaluation_parse_error.py
  moview/modules/answer_evaluator/__init__.py
  moview/modules/answer_evaluator/answer_analyzer.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/modules/answer_evaluator/answer_scorer.py
  moview/repository/question_answer/question_answer_repository.py
  moview/service/answer_service.py
  moview/service/evaluation_service.py
  moview/utils/prompt_parser.py
  requirements.txt
  tests/modules/answer_evaluator/test_answer_analyzer.py
  tests/modules/answer_evaluator/test_answer_evaluator.py
  tests/modules/answer_evaluator/test_answer_scorer.py
  tests/repository/test_question_answer_repository.py
  tests/service/test_evaluation_service.py
  tests/utils/test_prompt_parser.py
Labels: feat

#93 request: evaluation 주석 및 로그 변경
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/service/evaluation_service.py
  tests/service/test_evaluation_service.py
Labels: request

#96 refactor: Evaluation API의 response에 question_id 추가
  README.md
  moview/controller/evaluation_controller.py
  moview/service/evaluation_service.py
  tests/service/test_evaluation_service.py
Labels: refactor

#97 feat: CORS Resource 변경
  app.py
Labels: feat

#98 Release v1
  README.md
  app.py
  moview/__init__.py
  moview/config/container/container_config.py
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/domain/entity/question_answer/answer.py
  moview/environment/llm_factory.py
  moview/exception/__init__.py
  moview/exception/evaluation_parse_error.py
  moview/modules/answer_evaluator/__init__.py
  moview/modules/answer_evaluator/answer_analyzer.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/modules/answer_evaluator/answer_scorer.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/repository/question_answer/question_answer_repository.py
  moview/service/answer_service.py
  moview/service/evaluation_service.py
  moview/service/input_data_service.py
  moview/utils/async_controller.py
  moview/utils/prompt_parser.py
  moview/utils/retry_decorator.py
  requirements.txt
  tests/modules/answer_evaluator/test_answer_analyzer.py
  tests/modules/answer_evaluator/test_answer_evaluator.py
  tests/modules/answer_evaluator/test_answer_scorer.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/input/test_input_analyzer.py
  tests/repository/test_question_answer_repository.py
  tests/service/test_evaluation_service.py
  tests/service/test_input_service.py
  tests/utils/test_prompt_parser.py
Labels: release

#99 hot-fix : 배포에서 db 연결이 안되는 오류 수정
  moview/repository/input_data/input_data_repository.py
  moview/repository/interview_repository.py
  moview/repository/question_answer/question_answer_repository.py
Labels: hotfix

#100 Release v1.1
  moview/repository/input_data/input_data_repository.py
  moview/repository/interview_repository.py
  moview/repository/question_answer/question_answer_repository.py
Labels: release

#102 Refactor: 코어 리팩토링
  README.md
  app.py
  moview/config/llm/__init__.py
  moview/config/llm/custom_callback_handler.py
  moview/environment/llm_factory.py
  moview/exception/initial_question_parse_error.py
  moview/exception/retry_execution_error.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/question_generator/followup_question_giver.py
  moview/utils/retry_decorator.py
  requirements.txt
Labels: refactor, remove
