Repository SWM14-Architect/moview-core-service, pull requests merged in 2023-07, with the labels that each got.

#7 chore: Windows OS용 가상 환경 라이브러리 추출
  environment-windows.yml
Labels: chore

#10 pycache 제외룰 적용
  .gitignore
  main.py
  moview/modules/analyzer/answer_analyzer.py
Labels: chore

#11 Module refactoring
  main.py
  moview/modules/analyzer/input_info_analyzer.py
  moview/modules/question_generator/follow_up_question_generator.py
  moview/modules/question_generator/init_question_generator.py
Labels: fix, refactor

#12 Flask API 기능 추가
  API_Spec.md
  app.py
  environment-windows.yml
  moview/__init__.py
  moview/controller/__init__.py
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
  moview/utils/data_manager.py
Labels: feat, chore

#14 Flask 코드 리팩토링
  moview/controller/__init__.py
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
  moview/utils/data_manager.py
Labels: refactor

#18 Add test
  moview/log/__init__.py
  moview/modules/analyzer/answer_analyzer.py
  moview/modules/analyzer/input_info_analyzer.py
  tests/controller/__init__.py
  tests/controller/test_evaluation_controller.py
  tests/controller/test_generation_controller.py
  tests/modules/analyzer/__init__.py
  tests/modules/analyzer/test_answer_analyzer.py
  tests/modules/analyzer/test_input_info_analyzer.py
  tests/modules/prompter/test_question_prompter.py
  tests/modules/question_generator/__init__.py
Labels: refactor, test

#17 CI/CD 파이프라인 구축
  .github/workflows/cicd.yml
  .gitignore
  appspec.yml
  environment-windows.yml
  environment.yml
  moview/utils/data_manager.py
  requirements.txt
  scripts/deploy.sh
  scripts/install_dependencies.sh
  scripts/install_packages.sh
  scripts/stop_application.sh
Labels: fix, refactor, feat

#24 EC2의 module import error 해결
  .github/workflows/cicd.yml
  moview/__init__.py
  moview/controller/__init__.py
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
Labels: fix

#27 frontend ci/cd와 주석 및 코드 통일
  .github/workflows/cicd.yml
Labels: refactor, comment

#28 Add log
  .gitignore
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
  moview/modules/analyzer/answer_analyzer.py
  moview/modules/analyzer/input_info_analyzer.py
  moview/modules/prompter/question_prompter.py
  moview/modules/question_generator/follow_up_question_generator.py
  moview/modules/question_generator/init_question_generator.py
  moview/utils/util.py
  tests/controller/test_evaluation_controller.py
  tests/controller/test_generation_controller.py
  tests/modules/analyzer/test_answer_analyzer.py
  tests/modules/analyzer/test_input_info_analyzer.py
  tests/modules/prompter/test_question_prompter.py
  tests/modules/question_generator/test_prompt_convert_to_str.py
Labels: feat, test

#30 chore: coverage 패키지 추가
  .github/workflows/cicd.yml
  requirements.txt
Labels: refactor, chore

#31 Refactoring data manager code
  main.py
  moview/controller/__init__.py
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
  moview/modules/analyzer/answer_analyzer.py
  moview/modules/analyzer/input_info_analyzer.py
  moview/modules/prompter/__init__.py
  moview/modules/prompter/question_prompter.py
  moview/modules/question_generator/follow_up_question_generator.py
  moview/modules/question_generator/init_question_generator.py
  moview/utils/data_manager.py
Labels: refactor, remove

#32 Upgrade followup
  .gitignore
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_subcategory_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/modules/question_generator/followup_question_manager.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_category_classifier.py
  tests/modules/question_generator/test_followup_giver.py
  tests/modules/question_generator/test_followup_manager.py
  tests/modules/question_generator/test_prompt_convert_to_str.py
  tests/modules/question_generator/test_subcategory_classifier.py
Labels: feat, test

#34 Refactor/mongodb logger
  .github/workflows/cicd.yml
  appspec.yml
  moview/handlers/__init__.py
  moview/handlers/mongo_handler.py
  moview/loggers/__init__.py
  moview/loggers/mongo_logger.py
  requirements.txt
  scripts/after_install/install_aws_cli.sh
  scripts/after_install/install_packages.sh
  scripts/after_install/set_environment_variables.sh
  scripts/application_start/deploy.sh
  scripts/application_stop/stop_application.sh
  scripts/before_install/install_mongodb.sh
  scripts/before_install/install_python_dependencies.sh
  tests/handlers/__init__.py
  tests/handlers/test_mongo_handler.py
  tests/loggers/__init__.py
  tests/loggers/test_mongo_logger.py
Labels: refactor, test

#36 !HOTFIX: 권한 부족으로 인한 AWS CLI 설치 오류 해결
  scripts/after_install/install_aws_cli.sh
Labels: hotfix

#39 Answer service
  moview/controller/answer_controller.py
  moview/modules/answer_evaluator/__init__.py
  moview/modules/answer_evaluator/interview_answer_scorer.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_subcategory_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/modules/question_generator/followup_question_manager.py
  moview/service/__init__.py
  moview/service/answer_service.py
  moview/service/input_service.py
  moview/service/interview_action_enum.py
  moview/service/interviewee_data_vo.py
  tests/modules/answer_evaluator/__init__.py
  tests/modules/answer_evaluator/test_interview_answer_scorer.py
  tests/modules/prompter/test_question_prompter.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_followup_manager.py
  tests/service/__init__.py
  tests/service/test_answer_service.py
  tests/service/test_interview_data_vo.py
Labels: refactor, feat, test

#37 refactor: CI/CD 로직 추가
  .github/workflows/cicd.yml
Labels: refactor

#45 Service of input and score
  README.md
  moview/controller/answer_controller.py
  moview/modules/answer_evaluator/interview_answer_scorer.py
  moview/modules/initial_input/__init__.py
  moview/modules/initial_input/initial_input_analyzer.py
  moview/modules/initial_input/initial_question_giver.py
  moview/service/__init__.py
  moview/service/answer_service.py
  moview/service/input_service.py
  moview/service/interviewee_data_vo.py
  moview/service/score_service.py
  resources/interviewee_analysis.png
  resources/interviewee_answer.png
  tests/controller/test_evaluation_controller.py
  tests/controller/test_generation_controller.py
  tests/modules/analyzer/test_answer_analyzer.py
  tests/modules/analyzer/test_input_info_analyzer.py
  tests/modules/initial_input/__init__.py
  tests/modules/initial_input/test_inital_input_analyzer.py
  tests/modules/initial_input/test_inital_question_giver.py
  tests/modules/question_generator/test_followup_manager.py
  tests/service/test_answer_service.py
  tests/service/test_input_service.py
  tests/service/test_interview_data_vo.py
  tests/service/test_score_service.py
Labels: doc s, refactor, feat, test

#46 Singleton json loader
  README.md
  moview/modules/answer_evaluator/interview_answer_scorer.py
  moview/modules/initial_input/initial_input_analyzer.py
  moview/modules/initial_input/initial_question_giver.py
  moview/modules/prompt_loader/__init__.py
  moview/modules/prompt_loader/json/helpme.md
  moview/modules/prompt_loader/prompt_loader.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_subcategory_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/input_service.py
  moview/service/score_service.py
  resources/interviewee_feedback.png
  tests/modules/answer_evaluator/test_interview_answer_scorer.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_category_classifier.py
  tests/modules/question_generator/test_followup_giver.py
  tests/modules/question_generator/test_subcategory_classifier.py
  tests/prompt_loader/__init__.py
  tests/prompt_loader/test_prompt_loader.py
Labels: doc s, refactor, feat, test

#47 Refactor and rename
  README.md
  moview/__init__.py
  moview/controller/__init__.py
  moview/controller/evaluation_controller.py
  moview/controller/generation_controller.py
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_feedback_controller.py
  moview/controller/interviwee_input_controller.py
  moview/modules/analyzer/__init__.py
  moview/modules/analyzer/answer_analyzer.py
  moview/modules/analyzer/input_info_analyzer.py
  moview/modules/answer_evaluator/interview_answer_scorer.py
  moview/modules/initial_input/initial_input_analyzer.py
  moview/modules/initial_input/initial_question_giver.py
  moview/modules/prompt_loader/__init__.py
  moview/modules/prompt_loader/prompt_loader.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_subcategory_classifier.py
  moview/modules/question_generator/follow_up_question_generator.py
  moview/modules/question_generator/followup_question_giver.py
  moview/modules/question_generator/init_question_generator.py
  moview/service/__init__.py
  moview/service/interviewee_answer/__init__.py
  moview/service/interviewee_answer/interview_action_enum.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_data_vo.py
  moview/service/interviewee_input/__init__.py
  moview/service/interviewee_input/input_service.py
  moview/service/interviewee_rate/__init__.py
  moview/service/interviewee_rate/interviewee_answer_score_service.py
  moview/utils/data_manager.py
  moview/utils/llm_interface.py
  moview/utils/singleton_meta_class.py
  resources/interviewee_input.png
  tests/common_code_for_test.py
  tests/modules/answer_evaluator/test_interview_answer_scorer.py
  tests/modules/initial_input/test_inital_input_analyzer.py
  tests/modules/initial_input/test_inital_question_giver.py
  tests/modules/prompt_loader/__init__.py
  tests/modules/prompt_loader/test_prompt_loader.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_category_classifier.py
  tests/modules/question_generator/test_followup_giver.py
  tests/modules/question_generator/test_subcategory_classifier.py
  tests/service/test_answer_service.py
  tests/service/test_input_service.py
  tests/service/test_score_service.py
  tests/utils/test_llm_interface.py
Labels: doc s, refactor, rename, remove

#48 Refactor & Feat: Github Actions workflow 수정 & AWS SSM을 이용한 환경 변수 관리 기능 추가
  .github/workflows/cicd.yml
  .github/workflows/pr_test.yml
  .github/workflows/push_test_and_deploy.yml
  appspec.yml
  moview/handlers/mongo_handler.py
  moview/utils/aws_interface.py
  moview/utils/llm_interface.py
  requirements.txt
  scripts/after_install/set_environment_variables.sh
  scripts/before_install/set_environment_variables.sh
Labels: refactor, feat

#49 fix: jobs 분리로 인한 zip 파일 생성 오류 해결
  .github/workflows/dev_push.yml
  .github/workflows/main_pr.yml
  .github/workflows/main_push.yml
Labels: fix

#50 Fix prompt retry
  moview/controller/__init__.py
  moview/environment/__init__.py
  moview/environment/environment_loader.py
  moview/environment/llm_factory.py
  moview/handlers/mongo_handler.py
  moview/modules/answer_evaluator/interview_answer_scorer.py
  moview/modules/initial_input/initial_input_analyzer.py
  moview/modules/initial_input/initial_question_giver.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_subcategory_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/interviewee_input/input_service.py
  moview/utils/aws_interface.py
  tests/service/test_input_service.py
  tests/utils/test_llm_interface.py
Labels: fix, rename

#52 refactor: 환경 변수 호출 로직 정리
  moview/environment/environment_loader.py
  moview/environment/llm_factory.py
  moview/handlers/mongo_handler.py
Labels: refactor
