Repository SWM14-Architect/moview-core-service, pull requests merged in 2023-08, with the labels that each got.

#54 Feat add repository
  moview/repository/__init__.py
  moview/repository/entity/__init__.py
  moview/repository/entity/interviewee_data_main_document.py
  moview/repository/entity/interviewee_data_subdocument.py
  moview/repository/interviewee_data_repository.py
  moview/service/interviewee_input/input_service.py
  tests/modules/answer_evaluator/test_interview_answer_scorer.py
  tests/modules/initial_input/test_inital_input_analyzer.py
  tests/modules/initial_input/test_inital_question_giver.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_category_classifier.py
  tests/modules/question_generator/test_followup_giver.py
  tests/modules/question_generator/test_subcategory_classifier.py
  tests/repository/__init__.py
  tests/repository/test_interviewee_data_repository.py
  tests/service/test_input_service.py
  tests/utils/test_llm_interface.py
Labels: refactor, test

#55 Rename pr #54
  moview/controller/interviewee_answer_controller.py
  moview/modules/answer_evaluator/__init__.py
  moview/modules/answer_evaluator/answer_scorer.py
  moview/modules/initial_input/__init__.py
  moview/modules/input/__init__.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/prompt_loader/prompt_loader.py
  moview/repository/entity/interviewee_data_main_document.py
  moview/repository/entity/interviewee_data_subdocument.py
  moview/repository/interviewee_data_repository.py
  moview/service/__init__.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_answer/interviewer_action_enum.py
  moview/service/interviewee_input/interviewee_input_service.py
  moview/service/interviewee_rate/interviewee_answer_score_service.py
  tests/modules/answer_evaluator/test_interview_answer_scorer.py
  tests/modules/input/__init__.py
  tests/modules/input/test_inital_input_analyzer.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/prompt_loader/test_prompt_loader.py
  tests/repository/test_interviewee_data_repository.py
  tests/service/test_answer_service.py
  tests/service/test_input_service.py
  tests/service/test_rate_service.py
Labels: rename

#56 Rename/test files
  .github/workflows/dev_push.yml
  .github/workflows/main_pr.yml
  .github/workflows/main_push.yml
  moview/modules/prompt_loader/prompt_loader.py
  moview/modules/question_generator/__init__.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  tests/modules/answer_evaluator/test_answer_scorer.py
  tests/modules/input/test_input_analyzer.py
  tests/modules/question_generator/test_answer_category_classifier.py
  tests/modules/question_generator/test_answer_sub_category_classifier.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/service/interviewee_answer/__init__.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_input/__init__.py
  tests/service/interviewee_input/test_interviewee_input_service.py
  tests/service/interviewee_rate/__init__.py
  tests/service/interviewee_rate/test_interviewee_answer_score_service.py
Labels: rename

#57 Refactor answer and score
  moview/repository/entity/interviewee_data_main_document.py
  moview/repository/entity/interviewee_data_subdocument.py
  moview/repository/interviewee_data_repository.py
  moview/service/__init__.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_data_vo.py
  moview/service/interviewee_rate/interviewee_answer_score_service.py
  tests/repository/test_interviewee_data_repository.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_input/test_interviewee_input_service.py
  tests/service/interviewee_rate/test_interviewee_answer_score_service.py
Labels: refactor, test

#61 Feat add controller
  README.md
  moview/__init__.py
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_session_controller.py
  moview/controller/interviwee_input_controller.py
  moview/repository/entity/interviewee_data_main_document.py
  moview/repository/entity/interviewee_data_subdocument.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_answer/interviewer_action_enum.py
  moview/service/interviewee_input/interviewee_input_service.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_input/test_interviewee_input_service.py
Labels: feat, test

#65 Test and fix
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_session_controller.py
  moview/controller/interviwee_input_controller.py
  moview/repository/entity/interviewee_data_subdocument.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
  moview/service/interviewee_input/interviewee_input_service.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
  tests/service/interviewee_input/test_interviewee_input_service.py
Labels: fix

#66 Feat/controller finalize
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_feedback_controller.py
  moview/repository/entity/interviewee_data_main_document.py
  moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
  moview/service/interviewee_feedback/__init__.py
  moview/service/interviewee_feedback/interviewee_feedback_service.py
  tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
  tests/service/interviewee_feedback/__init__.py
  tests/service/interviewee_feedback/test_interviewee_feedback_service.py
Labels: feat

#67 refactor: logger 인자명 변경 및 feedback_controller에 logging 추가
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_feedback_controller.py
  moview/controller/interviewee_session_controller.py
  moview/controller/interviwee_input_controller.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_input/interviewee_input_service.py
Labels: refactor

#69 fix: cors 오류 수정
  app.py
  requirements.txt
Labels: fix

#70 Docs v1
  API_Spec.md
  README.md
  USECASE.md
  resources/CreateQuestionDiagram.png
  resources/MainFlow.png
  resources/interviewee_answer.png
  resources/interviewee_feedback.png
  resources/interviewee_input.png
Labels: doc s

#73 refactor: logger 종류 변경
  input.json
  moview/modules/answer_evaluator/answer_analyzer.py
  moview/modules/answer_evaluator/answer_scorer.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
  moview/utils/util.py
  tests/loggers/test_mongo_logger.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/input/test_input_analyzer.py
  tests/modules/question_generator/test_answer_category_classifier.py
  tests/modules/question_generator/test_answer_filter.py
  tests/modules/question_generator/test_answer_sub_category_classifier.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
  tests/service/interviewee_feedback/test_interviewee_feedback_service.py
  tests/service/interviewee_input/test_interviewee_input_service.py
Labels: refactor

#74 fix: Request Timeout 600s > 60s
  moview/environment/llm_factory.py
Labels: fix

#78 Rename move module
  README.md
  moview/config/__init__.py
  moview/config/db/__init__.py
  moview/config/db/mongo_config.py
  moview/config/db/mongo_handler.py
  moview/config/llm/__init__.py
  moview/config/llm/custom_callback_handler.py
  moview/config/loggers/__init__.py
  moview/config/loggers/mongo_logger.py
  moview/controller/interviewee_answer_controller.py
  moview/controller/interviewee_feedback_controller.py
  moview/controller/interviewee_session_controller.py
  moview/controller/interviwee_input_controller.py
  moview/domain/__init__.py
  moview/domain/entity/__init__.py
  moview/domain/entity/interviewee_data_main_document.py
  moview/domain/entity/interviewee_data_subdocument.py
  moview/modules/answer_evaluator/answer_analyzer.py
  moview/modules/answer_evaluator/answer_scorer.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/prompt_loader/__init__.py
  moview/modules/question_generator/answer_category_classifier.py
  moview/modules/question_generator/answer_filter.py
  moview/modules/question_generator/answer_sub_category_classifier.py
  moview/modules/question_generator/followup_question_giver.py
  moview/repository/interviewee_data_repository.py
  moview/service/interviewee_answer/interviewee_answer_service.py
  moview/service/interviewee_evaluation/interviewee_answer_evaluation_service.py
  moview/service/interviewee_input/interviewee_input_service.py
  moview/utils/__init__.py
  moview/utils/prompt_loader/__init__.py
  moview/utils/prompt_loader/json/helpme.md
  moview/utils/prompt_loader/prompt_loader.py
  tests/handlers/test_mongo_handler.py
  tests/repository/test_interviewee_data_repository.py
  tests/service/interviewee_answer/test_interviewee_answer_service.py
  tests/service/interviewee_evaluation/test_interviewee_answer_evaluation_service.py
  tests/service/interviewee_feedback/test_interviewee_feedback_service.py
  tests/utils/prompt_loader/__init__.py
  tests/utils/prompt_loader/test_prompt_loader.py
Labels: doc s, rename
