Repository SWM14-Architect/moview-core-service, pull requests merged in 2023-10, with the labels that each got.

#107 Feat/tts and stt
  app.py
  moview/controller/stt_controller.py
  moview/controller/tts_controller.py
  moview/environment/environment_loader.py
  moview/exception/stt_error.py
  moview/utils/stt.py
  moview/utils/tts.py
Labels: feat

#109 refactor: prompt_loader가 parameter store를 사용하도록 변경
  moview/utils/prompt_loader.py
  moview/utils/prompt_loader/__init__.py
  moview/utils/prompt_loader/json/helpme.md
Labels: refactor

#108 feat: 컨트롤러 오류 예외처리
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/controller/oauth/oauth_controller.py
  moview/controller/stt_controller.py
  moview/controller/tts_controller.py
  moview/modules/input/input_analyzer.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/input_data_service.py
  moview/service/light_mode_service.py
  moview/utils/retry_decorator.py
Labels: feat

#110 feat: 입력 글자수 제한을 위한 검증 로직 추가
  moview/controller/answer_controller.py
  moview/controller/constants/__init__.py
  moview/controller/constants/answer_contants.py
  moview/controller/constants/input_data_constants.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/controller/stt_controller.py
  moview/controller/tts_controller.py
  moview/decorator/__init__.py
  moview/decorator/retry_decorator.py
  moview/decorator/timing_decorator.py
  moview/decorator/validation_decorator.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/modules/input/initial_question_giver.py
  moview/modules/light/light_question_giver.py
Labels: feat

#111 !HOTFIX: 잘못된 import 경로 수정 및 테스트 수정
  moview/modules/input/input_analyzer.py
  moview/modules/question_generator/followup_question_giver.py
  tests/service/test_input_service.py
  tests/service/test_light_mode_service.py
Labels: hotfix

#114 Fix/dev cicd
  app.py
  appspec.yml
  requirements.txt
  scripts/before_install/install_mongodb.sh
  scripts/before_install/install_python_dependencies.sh
Labels: fix

#116 Feat: Slack Feedback API 추가
  README.md
  app.py
  moview/controller/constants/slack_contants.py
  moview/controller/slack_controller.py
  requirements.txt
Labels: feat, chore

#117 Fix: Interview Document
  app.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/environment/environment_loader.py
  moview/repository/interview_repository.py
  moview/service/answer_service.py
  moview/service/interview_service.py
  requirements.txt
  scripts/application_start/deploy.sh
Labels: fix, refactor

#118 Refactor/logger logic
  app.py
  moview/config/db/mongo_handler.py
  moview/config/loggers/mongo_logger.py
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/controller/oauth/oauth_controller.py
  moview/controller/stt_controller.py
  moview/controller/tts_controller.py
  moview/repository/interview_repository.py
  moview/repository/user/user_repository.py
  moview/service/user_service.py
  tests/modules/input/test_inital_question_giver.py
Labels: refactor

#123 !HOTFIX: Cross Domain Cookie
  app.py
  moview/config/jwt/jwt_config.py
  scripts/application_start/deploy.sh
  scripts/application_stop/stop_application.sh
Labels: hotfix

#122 fix: input_data_document의 잘못된 타입으로 인한 오류 수정
  app.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/service/interview_service.py
Labels: fix

#124 Fix: Environment Setting
  moview/config/jwt/jwt_config.py
  moview/environment/environment_loader.py
Labels: fix, refactor

#125 Refactor/seperate main and dev
  .github/workflows/dev_pr.yml
  .github/workflows/dev_push.yml
  .github/workflows/feat_push.yml
  .github/workflows/main_push.yml
  appspec-dev.yml
  appspec-main.yml
  scripts/before_install/set_environment_variables_dev.sh
  scripts/before_install/set_environment_variables_main.sh
Labels: refactor

#126 feat: 배포 직전에 환경 변수를 로딩하는 로직 추가
  scripts/application_start/deploy.sh
Labels: feat

#128 Refactor/cicd stop application
  scripts/application_start/deploy.sh
  scripts/application_stop/stop_application.sh
  scripts/before_install/set_environment_variables_dev.sh
  scripts/before_install/set_environment_variables_main.sh
Labels: bug

#132 Release v3.1
  .github/workflows/dev_pr.yml
  .github/workflows/dev_push.yml
  .github/workflows/feat_push.yml
  .github/workflows/main_push.yml
  app.py
  appspec-dev.yml
  appspec-main.yml
  moview/config/jwt/jwt_config.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/environment/environment_loader.py
  moview/service/interview_service.py
  scripts/application_start/deploy.sh
  scripts/application_stop/stop_application.sh
  scripts/before_install/set_environment_variables_dev.sh
  scripts/before_install/set_environment_variables_main.sh
Labels: release

#135 langchain 걷어내기 (10.23 리뷰 바람)
  app.py
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/decorator/retry_decorator.py
  moview/environment/llm_factory.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/light/light_question_giver.py
  moview/modules/question_generator/followup_question_giver.py
  moview/service/input_data_service.py
  tests/modules/answer_evaluator/test_answer_evaluator.py
  tests/modules/async/test_async_call.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/input/test_input_analyzer.py
  tests/modules/light/test_light_question_giver.py
  tests/modules/question_generator/test_followup_question_giver.py
Labels: refactor, test

#137 Feat: health check api
  app.py
  moview/controller/health_controller.py
Labels: feat

#139 Feat/eb
  .dockerignore
  .ebextensions/01-setup-timezone.config
  .ebextensions/02-setup-mongodb.config
  .elasticbeanstalk/config.yml
  .gitignore
  Dockerfile
  Dockerrun.aws.json
  moview/config/db/mongo_constant.py
  moview/config/db/mongo_handler.py
  moview/environment/environment_loader.py
  moview/repository/input_data/input_data_repository.py
  moview/repository/interview_repository.py
  moview/repository/question_answer/question_answer_repository.py
  moview/repository/user/user_repository.py
  requirements.txt
Labels: feat

#141 Release v3.2
  .dockerignore
  .ebextensions/01-setup-timezone.config
  .ebextensions/02-setup-mongodb.config
  .elasticbeanstalk/config.yml
  .gitignore
  Dockerfile
  Dockerrun.aws.json
  app.py
  moview/config/db/mongo_constant.py
  moview/config/db/mongo_handler.py
  moview/controller/answer_controller.py
  moview/controller/evaluation_controller.py
  moview/controller/feedback_controller.py
  moview/controller/health_controller.py
  moview/controller/input_data_controller.py
  moview/controller/light_mode_controller.py
  moview/controller/oauth/oauth_controller.py
  moview/decorator/retry_decorator.py
  moview/domain/entity/input_data/coverletter_document.py
  moview/domain/entity/input_data/initial_input_data_document.py
  moview/domain/entity/interview_document.py
  moview/domain/entity/question_answer/answer_document.py
  moview/domain/entity/question_answer/question_document.py
  moview/domain/entity/user/user_document.py
  moview/environment/environment_loader.py
  moview/environment/llm_factory.py
  moview/modules/answer_evaluator/answer_evaluator.py
  moview/modules/input/initial_question_giver.py
  moview/modules/input/input_analyzer.py
  moview/modules/light/light_question_giver.py
  moview/modules/question_generator/followup_question_giver.py
  moview/repository/input_data/input_data_repository.py
  moview/repository/interview_repository.py
  moview/repository/question_answer/question_answer_repository.py
  moview/repository/user/user_repository.py
  moview/service/answer_service.py
  moview/service/input_data_service.py
  moview/service/light_mode_service.py
  moview/service/user_service.py
  requirements.txt
  tests/modules/answer_evaluator/test_answer_evaluator.py
  tests/modules/async/test_async_call.py
  tests/modules/input/test_inital_question_giver.py
  tests/modules/input/test_input_analyzer.py
  tests/modules/light/test_light_question_giver.py
  tests/modules/question_generator/test_followup_question_giver.py
  tests/repository/test_question_answer_repository.py
  tests/repository/test_user_repository.py
  tests/service/test_answer_service.py
  tests/service/test_evaluation_service.py
  tests/service/test_feedback_service.py
Labels: release
